extends: 'eslint:recommended'
env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
parserOptions:
  sourceType: module
rules:
  no-undefined: off
  no-var: off
  camelcase:
    - error
    - properties: never
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  max-nested-callbacks:
    - error
    - 5
