language: node_js
sudo: false
node_js: '8'
cache:
  directories:
  - node_modules
install: npm install
script: npm test
deploy:
  - provider: npm
    email: hanifbbz@gmail.com
    api_key:
      secure: vXtC7xn3q9xssFxMrPQaDcUQhq5raq6htm0JpqMnB1az++ynMTbm3zaZuU5QDBKy6zyyXV0u8PPpyY+c43VbOUyV9nCYSMRomo/UffgMQi1NUjNWtncPNH4/Y8C5T+fcn74/Le6eJjvfMayCyuKA22phka3dehgeE5bwLpsT5AegaEXlypxiohS2WQjroHpQnf3t5qYgpFcXsx1RXtLNO+8xj7AqKQl4FvmjrVJqi+dA2bBVGgSng9/iB80BCUUcAbD+rHZ04+pfDawTcGJGsqIxLdsDaNgFWErhXHAzDVgSgqaAGLqCfj7Rk13SELIFbqaKgUXTrwuSpUwl+I06DeOn4Nnwy9FZubykFkRLhnr5Dpg6+/9U/TYav9u1H56i14Yg6hwXUvSSSN+wfrLO7P86cdRFVbXfucnKFiKN9djFfIOYxM6Wte5htWxulNMbHhzqFen9LZpADr4KT59YsYQMIShMlcwhN8I2i3+OHrLayNSmHUVZS0gItqtXnG+XLT6jhETOcjMvTyIPc2uZkLTVPzEf2aAnmXfIMk/V0lSeI1XLSK4aOXb2wIktYr/XX3qgKuVpPPV45ziJ4tlK/PjdyjKWBPHozBSxmzLWpDEG6wGreYit4yIpUoo1A3KDeg/uz+aWbf2gmgbcI9B0IUDwEt7NrK1pq51D3Roolmw=
    on:
      tags: true
      repo: schibsted/browser-sdk
  - provider: s3
    access_key_id: AKIAIDSHJ72T7G53A7GA
    secret_access_key:
      secure: VL53BKF6O38D5GE+NCLHbXdtC+lA+XaGg7GWmnObGXRUlaCURtm+fxsOtTRBPFCeFjg0bl/UW1ylQhZFF8UEkzYrH+MDjpcMICZQmBTry7sTxgk8yj8H/Ib+op2Gc7p8CN8PQIaJHth1uKklPEX5t9ELkFFsJkhQpTDqTFpE5/M=
    bucket: cdn.spid.se
    region: eu-west-1
    detect_encoding: true
    cache_control: "no-transform,public,max-age=31536000"
    local-dir: dist
    upload-dir: "$TRAVIS_TAG"
    acl: public_read
    skip_cleanup: true
    on:
      repo: schibsted/browser-sdk
      tags: true
