language: node_js
sudo: false
node_js: '8'
cache:
  directories:
  - node_modules
install: npm install
script: npm test
deploy:
  - provider: npm
    email: hanifbbz@gmail.com
    api_key:
      secure: vXtC7xn3q9xssFxMrPQaDcUQhq5raq6htm0JpqMnB1az++ynMTbm3zaZuU5QDBKy6zyyXV0u8PPpyY+c43VbOUyV9nCYSMRomo/UffgMQi1NUjNWtncPNH4/Y8C5T+fcn74/Le6eJjvfMayCyuKA22phka3dehgeE5bwLpsT5AegaEXlypxiohS2WQjroHpQnf3t5qYgpFcXsx1RXtLNO+8xj7AqKQl4FvmjrVJqi+dA2bBVGgSng9/iB80BCUUcAbD+rHZ04+pfDawTcGJGsqIxLdsDaNgFWErhXHAzDVgSgqaAGLqCfj7Rk13SELIFbqaKgUXTrwuSpUwl+I06DeOn4Nnwy9FZubykFkRLhnr5Dpg6+/9U/TYav9u1H56i14Yg6hwXUvSSSN+wfrLO7P86cdRFVbXfucnKFiKN9djFfIOYxM6Wte5htWxulNMbHhzqFen9LZpADr4KT59YsYQMIShMlcwhN8I2i3+OHrLayNSmHUVZS0gItqtXnG+XLT6jhETOcjMvTyIPc2uZkLTVPzEf2aAnmXfIMk/V0lSeI1XLSK4aOXb2wIktYr/XX3qgKuVpPPV45ziJ4tlK/PjdyjKWBPHozBSxmzLWpDEG6wGreYit4yIpUoo1A3KDeg/uz+aWbf2gmgbcI9B0IUDwEt7NrK1pq51D3Roolmw=
    on:
      tags: true
      repo: schibsted/browser-sdk
  - provider: s3
    access_key_id:
      secure: "XlWaP7SDaox03hBul0PPMBdavCJ0/3Ne4eVX0UdTVqWyUnKpeRvQ4qzKHz11YOcBCKwBXtWRssv+5EtmkGMuI6MS1l9vyRJaE+vDMN0vbtN+1Uq0VFewtL0Evl/DzvCgSLnFi6Dxj6rVtr3O8a4oWOT6jUPO1S6rwWDKMSqpg+kpmAbCpuk5bivQx5kHrGg+JtqpdBRA+PgaSz3vUGp1b9V5X1Fp8KCUn7lqsYTLjo/ahY8zAiAnFNmV4ZnPiTXGQd2QYyvq7ACKZZgE+uCOSftPg3qBH3YhT6weLxdIrHVgnSp2KeyDkKIpSe9X1Ptk7RxfIvqLLuMYT4WJBhaj3Nx+B4Y3baPzHOwXjHy4MJo1wM1sPPJrLPSVgaFg62r/xfU+RcaIOdR2pZE4wi76nwnZuN0KVBqXIMjE9ElnCTvQeFNUXmqJB88QOnxyTvfyUiCIQsw+3CseIy0GVnkp9CaalLT14zzlPtUxquhEtQL+IeTFqo7wNcIgzBO00PG0wSryjPqGqAhIRygbUE/ezrfwuPbmfYDSZcrMM6sab49CxiAIkb9Ayz70Qpd7O5laiyrIgIH2HBNoTw1zibcRo+/7VaJcd/2XhUdTSJXglVZ9S70wqE/VO69DU+BoDvz7/3sUZtes6WHvPBWTUdW3LLOiBsi0Egsmqkj54SycB2Y="
    secret_access_key:
      secure: "N9C9AUOSyl/gWKgaPHnTslsbFklLaPNL9BATm5sCO8tRlhraRlZpVltts3X99PEdCpiYA8lcImCiv0HrYF78QSipc0kDdWHQhn67ziP1dser99OdL8gJewjVTHOG7/T8p0X/LYi6NmgjLV9Q59gln3zlYDXH+tH9Jk6jRnDTGWCO70mx5OrcCsiaajCzzMcEcCZjsJrChM+8A5NL4ZzwKTq4hpfxbIGVs26c1VH6A2jvG+gB8kCiuonmxyqKmBG49fRD6gZlZgink+Ui4iiI3W9CxYVra0vpwgeb3bhk0OQfykedvcPBV4a+Cu2uImGNEwIRtM6MuKfxj4f8XMwzl1T0i2D7xevYyp84Yf2GFrWfAmpTWeYTN7UfOlzcp/RmkRj4innfAxfQ3N0GTFrbU8x8xI62qvm8bgm9T7CNzS+g007A10TqC9IIxCJjg6cVYgZ4Dx9YxiTvSuikeI8yQAmgSzkeja85/moK+rSVTKxzfvUWSKZsz1Hse+In7gsHsAvXrH37QQPPEkL1OgbQjRVo3zO3WDAWqEjwVku4Y6D1FDKGVXpj/KPKpm4JoYkpmydmB5kDAYBVPHtVuMT7wU26AcqWGf7jqXCeL+0MADVjtiTIAdyW4Lj0dz23ZAxigCgHAxkAdujXum4qGiQ8izaKZmvY4v3AsXxqeo3iJvg="
    bucket:
      secure: "NnofWFVE1mVDqOOwsHoAmLgCoTz7Fw8ltv0WBsKChTViUzDdNyMt/ntV9eevCLzNasMk3RcMn9vLXmK8iq/NtXK3gL5w+If+b3Eorik8FLWjSOR18XYMhFhBCQywntWi2I/CcnqlWHrhW5/NVSRPrhUUpcj8VuhUNOsQjlsDk+0c2O50vyWyS9l0NhaTvvcG3lyB9vX6hId1XT3WcRQKAJ+VJdsHBc57EL4HquAXJNFu91+vCuZeHqO9O5xch8gLtWa3A9489OtFp5z5c3ucmLbBGPw5Pzv0wdLwrnoH3OGyIwyPCfUtwRI+GdZylVwOBIZtlaK65WJe4fjD1xvs7MKuyM1yR6XgYLoNNujsdhRxGIlvFOWum2hJsAr/j2u19uM8GRRkiM1tBmMn8gu21o55FHskDNjJeatqp+FVX+Av3B+A1vF/yDdJ6LOOQ9/3tSv8ij6k9FCCrRVl4H0aWgDi8iGHaCs1nQFEx4U8Kes9L81tbkg8w/uVaCoH3b1bf/thYs2yENhY2pCIU5sTlG6qaiKu33bJwai3ujPpw2NTJtMNtxZnvpw5eAUBr4FBA6gHnC6r8xzHxJV4ODu+3lKU3ypXgT2SEHaLY2rN85LCxzVxPLR8cyA5Zyrk5Yac3Lrzr0hMD44L/1NIXpWRPhjnnAiFucSfTBIpUK1ProQ="
    region: eu-west-1
    detect_encoding: true
    cache_control: "no-transform,public,max-age=31536000"
    local-dir: dist
    upload-dir: "$TRAVIS_TAG"
    acl: public_read
    skip_cleanup: true
    on:
      repo: schibsted/browser-sdk
      tags: true
